### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by tomaszjacek** [HTDerekLiu/BlenderToolbox#1]
Hi,
How to use it? should I install it like addon? I'm asking because I did not installed it.
I have just unziped it entered 'cycles' folder and run with command.
G:\app\BlenderFoundation\Blender2.83\blender.exe --background --python demo_stone.py

here is an end of error message. looks that it doesnt see include.py file...

Thank you,
tj

    assign as a type annotation: OBJECT_OT_ahs_convert_curve_to_mesh.is_remove_doubles
    assign as a type annotation: OBJECT_OT_ahs_convert_curve_to_mesh.is_uv_pack_islands
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "G:\download\blender\BlenderToolbox-master\cycles\demo_stone.py", line 16, in <module>
    from include import *
ModuleNotFoundError: No module named 'include'

Blender quit

**Comment by HTDerekLiu** [comment]
Sorry for the extremely late reply. The error comes from not setting up the path correctly. In the template file, you should see this line
"sys.path.append('/Users/hsuehtil/Dropbox/BlenderToolbox/')"
You should replace this string '/Users/hsuehtil/Dropbox/BlenderToolbox/' with your local file path to the repository.
