### ISSUE TITLE
How to render a ply mesh that has its own color?

### ISSUE THREAD

**Issue by chirsyes** [HTDerekLiu/BlenderToolbox#10]
Greets, I note that your code can render the shape without any initialization color (texture). So if I want to render a mesh in (.ply) file form that has its own color (texture), which functions could I use or change? Thanks in advance.

**Comment by HTDerekLiu** [comment]
This function should be what you need to render a mesh with textures https://github.com/HTDerekLiu/BlenderToolbox/blob/master/demos/demo_texture.py
