### ISSUE TITLE
How to render this texture?

### ISSUE THREAD

**Issue by Fightzzw** [HTDerekLiu/BlenderToolbox#11]
Dear Derek,

Thanks for the great library.

I want to know how to render the following effect

![image](https://github.com/HTDerekLiu/BlenderToolbox/assets/45233826/4b2883c2-ec7e-4002-b80f-268625286707)

I think "demo_edge" is different from this one

![demo_edge](https://github.com/HTDerekLiu/BlenderToolbox/assets/45233826/13c000f5-b5da-47e9-89d2-6d8ff3d908f9)

**Comment by HTDerekLiu** [comment]
Oh do you mean rendering multiple objects in the same scene? If yes, you can simply do multiple times of `readMesh` and `setMat_edge` like
```
mesh = bt.readMesh(meshPath0, location, rotation, scale)
bt.setMat_edge(mesh, edgeThickness, edgeColor, meshRGBA, AOStrength)

mesh = bt.readMesh(meshPath1, location, rotation, scale)
bt.setMat_edge(mesh, edgeThickness, edgeColor, meshRGBA, AOStrength)

mesh = bt.readMesh(meshPath2, location, rotation, scale)
bt.setMat_edge(mesh, edgeThickness, edgeColor, meshRGBA, AOStrength)
```
in the same script by providing different mesh paths and enter their corresponding parameters.

**Comment by Fightzzw** [comment]
Sorry, I wasn't clear before, I wasn't trying to render multiple objects. Instead, I wanted to render individual objects. 

I would be grateful if you could answer my following question.

1. I want to know how to render objects **with sharp vertices and edges** as shown in the image below, as I found that the effect rendered using `setMat_edge` appears too smooth.
![image](https://github.com/HTDerekLiu/BlenderToolbox/assets/45233826/fe7a5c1a-4831-4cbc-8d90-452bb816f77a)

2. I want to know how to render objects **with sharp vertices without edges** as shown in the image below.
![image](https://github.com/HTDerekLiu/BlenderToolbox/assets/45233826/0a93428a-6cff-440e-bda1-0bdc42fbef73)

3. I want to know how to render objects **with sharp vertices and **thick** edges** as shown in the image below.
![image](https://github.com/HTDerekLiu/BlenderToolbox/assets/45233826/0cfabbec-25aa-4397-bdbf-54829cdcd3e9)

**Comment by HTDerekLiu** [comment]
> I want to know how to render objects with sharp vertices and edges as shown in the image below, as I found that the effect rendered using setMat_edge appears too smooth.

You just need to comment these out
```
bpy.ops.object.shade_smooth() 
bt.subdivision(mesh, level = 0)
```
> I want to know how to render objects with sharp vertices without edges as shown in the image below.

You can use https://github.com/HTDerekLiu/BlenderToolbox/blob/master/demos/demo_singleColor.py and with the above two lines commented out.

> I want to know how to render objects with sharp vertices and thick edges as shown in the image below.

This is a bit more complicated. You need to provide the edge information (in this case, all edges) and use this https://github.com/HTDerekLiu/BlenderToolbox/blob/master/demos/demo_edgeSubset.py.
