### ISSUE TITLE
'NoneType' object has no attribute 'nodes'

### ISSUE THREAD

**Issue by LordLiang** [HTDerekLiu/BlenderToolbox#2]
Dear HTDerekLiu,
I run your default template_pointcloud.py to render a point cloud on my macOS, but I got an error. Can you give me some advice?

```
(base) lord_liang@zhoujiedeMacBook-Pro BlenderToolbox % /Applications/Blender.app/Contents/MacOS/Blender --background --python template_pointcloud.py
Blender 3.2.0 (hash e05e1e369187 built 2022-06-08 10:34:50)
Read prefs: /Users/lord_liang/Library/Application Support/Blender/3.2/config/userpref.blend
========================================
You are using CPU rendering. Please see the [Notes] section on the GitHub if you want to switch to GPU rendering.
========================================

Successfully imported './meshes/spot_pt.ply' in 0.020 sec
Error: Python: Traceback (most recent call last):
  File "/Users/lord_liang/BlenderToolbox/template_pointcloud.py", line 28, in <module>
    bt.setMat_pointCloud(mesh, ptColor, ptSize)
  File "/Users/lord_liang/BlenderToolbox/BlenderToolBox/setMat_pointCloud.py", line 66, in setMat_pointCloud
    IN = tree.nodes['Group Input']
AttributeError: 'NoneType' object has no attribute 'nodes'

Blender quit
```

**Comment by HTDerekLiu** [comment]
Hi!! 

Sorry for the late reply. This bug is due to recent API changes from Blender 3.2 Alpha to Blender 3.2.x that `bpy.ops.object.modifier_add(type='NODES')` no longer creates a `node_group`. I just updated the `setMat_pointCloud.py` function, please pull it and let me know if there are further issues.

**Comment by LordLiang** [comment]
> Hi!!
> 
> Sorry for the late reply. This bug is due to recent API changes from Blender 3.2 Alpha to Blender 3.2.x that `bpy.ops.object.modifier_add(type='NODES')` no longer creates a `node_group`. I just updated the `setMat_pointCloud.py` function, please pull it and let me know if there are further issues.

Dear HTDerekLiu,
Thank you for your kind reply! My problem is solved now!
