### ISSUE TITLE
Create Citation

### ISSUE THREAD

**Issue by sbharadwajj** [HTDerekLiu/BlenderToolbox#21]
Hi,

Thanks for your wonderful repository. I wish to cite your repository because it has been very helpful for my projects. Could you please provide a citation that I can use? 

Regards,
Shrisha

**Comment by HTDerekLiu** [comment]
Glad to hear that this could be useful :) 
Just created a bibtex 
```
@software{Liu_BlenderToolbox_2018,
  author = {Liu, Hsueh-Ti Derek},
  month = {12},
  title = {{Blender Toolbox}},
  url = {https://github.com/HTDerekLiu/BlenderToolbox},
  year = {2018}
}
```
