### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by de-gozaru** [HTDerekLiu/BlenderToolbox#6]
Hi Derek,

Thank you for the great library.

Can you please provide an example of how to render an animation if it's possible, like those videos that show interpolation between two shapes, etc?

Keep up the good work.

Best,

**Comment by HTDerekLiu** [comment]
Hi,

Unfortunately, we don't have a fancy way to render the animation yet. Currently, we saved all the meshes of every frame and render them one-by-one into images. Then we use video editing softwares to turn those images into a video. 

-Derek
