### ISSUE TITLE
Vector field rendering

### ISSUE THREAD

**Issue by de-gozaru** [HTDerekLiu/BlenderToolbox#7]
Hi Derek,

Thank you for the great library.

Is it possible to provide an example rendering of a vector field on a mesh?

Keep up the good work.

Best,

**Comment by HTDerekLiu** [comment]
Thanks for pointing out. That function was broken due to recent API changes. But now is fixed!! You can find it in `demo_vectorField.py `

**Comment by HTDerekLiu** [comment]
`P` is the root location of each vector and `PN` is the orientation of that vector. 

For L37-48, it creates a triangle mesh where the face normal of the triangle is facing the direction of `PN`. This mesh will not appear in the rendering but the surface normal data will be used in the geometry nodes.

**Comment by HTDerekLiu** [comment]
yep that is correct!!
