### ISSUE TITLE
how to set the material of mesh

### ISSUE THREAD

**Issue by Wei-Qi** [HTDerekLiu/BlenderToolbox#9]
How to use my own defined material

**Comment by HTDerekLiu** [comment]
You could use `setMat_XXX` functions to do that. For instance, line 32 of this file https://github.com/HTDerekLiu/BlenderToolbox/blob/master/demos/demo_plastic.py

**Comment by Wei-Qi** [comment]
Thank you for your replay, i meet a new problem when i run the `template_lazy.py`.
```
 Python: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Admin\Desktop\BlenderToolbox-master\template_lazy.py", line 32, in <module>
    bt.render_mesh_default(arguments)
  File "C:\Users\Admin\Desktop\BlenderToolbox-master\BlenderToolBox\render_mesh_default.py", line 51, in render_mesh_default
    subdivision(mesh, level = args["subdivision_iteration"])
  File "C:\Users\Admin\Desktop\BlenderToolbox-master\BlenderToolBox\subdivision.py", line 19, in subdivision
    mesh.modifiers["Subdivision"].render_levels = level # rendering subdivision level
KeyError: 'bpy_prop_collection[key]: key "Subdivision" not found'
```

**Comment by HTDerekLiu** [comment]
This indeed looks like a version issue to me. Perhaps you could comment this line out https://github.com/HTDerekLiu/BlenderToolbox/blob/8044e77268ff018514ad1501c291f6deb6a07ec6/BlenderToolBox/render_mesh_default.py#L51 for now, which will prevent you to run subdivision. I will look into some recent Blender API updates when I have time.

**Comment by Wei-Qi** [comment]
what's your version?

**Comment by HTDerekLiu** [comment]
I am using Blender 3.4.1
